# Generated by Django 5.2.17 on 2026-09-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerieHistoricaDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año calendario del corte (ej. 2025 para el corte de septiembre 2025).')),
                ('fecha_corte', models.DateField(help_text='Fecha exacta del corte, ej. 2025-09-30 o 2024-12-31.')),
                ('tipo_deuda', models.CharField(choices=[('bruta', 'Deuda Bruta'), ('neta', 'Deuda Neta')], max_length=5)),
                ('moneda', models.CharField(choices=[('usd', 'Dólares'), ('clp', 'Pesos Chilenos')], max_length=3)),
                ('monto_millones', models.DecimalField(decimal_places=4, help_text='Monto en millones de la moneda correspondiente. Puede ser negativo (deuda neta).', max_digits=18)),
                ('pct_pib', models.DecimalField(blank=True, decimal_places=6, help_text='Deuda como porcentaje del PIB. Indiferente a la moneda: mismo valor esperado para USD y CLP dado el mismo (anio, tipo_deuda).', max_digits=8, null=True)),
                ('es_corte_parcial', models.BooleanField(default=False, help_text='True cuando fecha_corte no es el cierre de un año calendario completo (ej. el corte más reciente a mitad de período).')),
                ('fuente', models.CharField(default='series_historicas_deuda_hacienda', help_text='Identificador del dataset de origen.', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Momento en que esta fila fue ingestada, para detectar revisiones de cifras históricas entre cargas sucesivas del mismo archivo.')),
            ],
            options={
                'verbose_name': 'Serie Histórica de Deuda',
                'verbose_name_plural': 'Series Históricas de Deuda',
                'ordering': ['anio', 'tipo_deuda', 'moneda'],
                'indexes': [models.Index(fields=['anio', 'tipo_deuda', 'moneda'], name='data_engine_anio_ac03ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('fecha_corte', 'tipo_deuda', 'moneda'), name='unique_deuda_corte_tipo_moneda')],
            },
        ),
    ]
