# Generated by Django 5.2.17 on 2026-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriehistoricadeuda',
            name='fuente',
            field=models.CharField(default='hacienda_series_historicas_deuda', help_text='Identificador del dataset de origen.', max_length=100),
        ),
        migrations.CreateModel(
            name='ComposicionDeudaAcreedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_corte', models.DateField()),
                ('categoria', models.CharField(choices=[('banco_central_chile', 'Banco Central de Chile'), ('birf', 'Banco Internacional de Reconstrucción y Fomento (BIRF)'), ('bid', 'Banco Interamericano de Desarrollo (BID)'), ('bonos', 'Bonos'), ('eximbank_japon', 'Eximbank Japón'), ('bancoestado_chile', 'BancoEstado de Chile'), ('aid', 'Agencia Internacional de Desarrollo (AID)'), ('otros', 'Otros')], max_length=32)),
                ('monto_millones', models.DecimalField(decimal_places=6, max_digits=18)),
                ('es_corte_parcial', models.BooleanField(default=False)),
                ('fuente', models.CharField(default='hacienda_composicion_deuda', max_length=64)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['anio', 'categoria'], name='data_engine_anio_44bb77_idx')],
                'constraints': [models.UniqueConstraint(fields=('fecha_corte', 'categoria'), name='unique_composicion_acreedor_corte_categoria')],
            },
        ),
        migrations.CreateModel(
            name='ComposicionDeudaLegislacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_corte', models.DateField()),
                ('categoria', models.CharField(choices=[('deuda_interna', 'Deuda Interna'), ('deuda_externa', 'Deuda Externa')], max_length=32)),
                ('monto_millones', models.DecimalField(decimal_places=6, max_digits=18)),
                ('es_corte_parcial', models.BooleanField(default=False)),
                ('fuente', models.CharField(default='hacienda_composicion_deuda', max_length=64)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['anio', 'categoria'], name='data_engine_anio_865661_idx')],
                'constraints': [models.UniqueConstraint(fields=('fecha_corte', 'categoria'), name='unique_composicion_legislacion_corte_categoria')],
            },
        ),
        migrations.CreateModel(
            name='ComposicionDeudaMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_corte', models.DateField()),
                ('categoria', models.CharField(choices=[('dolares_usa', 'Dólares USA'), ('uf', 'Unidades de Fomento Chile'), ('pesos', 'Pesos'), ('unidad_cuenta_bid', 'Unidad de Cuenta BID'), ('unidad_canasta_birf', 'Unidad de Canasta BIRF'), ('yen_japones', 'Yen Japonés'), ('euros', 'Euros'), ('marco_aleman', 'Marco Alemán'), ('otras', 'Otras')], max_length=32)),
                ('monto_millones', models.DecimalField(decimal_places=6, max_digits=18)),
                ('es_corte_parcial', models.BooleanField(default=False)),
                ('fuente', models.CharField(default='hacienda_composicion_deuda', max_length=64)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['anio', 'categoria'], name='data_engine_anio_34f30a_idx')],
                'constraints': [models.UniqueConstraint(fields=('fecha_corte', 'categoria'), name='unique_composicion_moneda_corte_categoria')],
            },
        ),
    ]
