# Generated by Django 5.2.17 on 2026-09-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0002_alter_seriehistoricadeuda_fuente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTituloDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(choices=[('pagares_banco_central', 'Pagarés de Banco Central'), ('certificados_deposito_plazo', 'Certificados de depósitos a plazo'), ('efectos_comercio', 'Efectos de comercio'), ('bonos_banco_central', 'Bonos de Banco Central'), ('bonos_bancos_cooperativas', 'Bonos de Bancos y cooperativas'), ('bonos_otros_intermediarios_financieros', 'Bonos de Otros intermediarios financieros'), ('bonos_empresas_no_financieras', 'Bonos de Empresas no financieras'), ('bonos_gobierno_general', 'Bonos de Gobierno general'), ('bonos_no_residentes', 'Bonos de No residentes (Mercado local)')], max_length=50)),
                ('tenedor', models.CharField(blank=True, choices=[('banco_central', 'Banco Central'), ('bancos_cooperativas', 'Bancos y cooperativas'), ('fondos_mutuos_inversion', 'Fondos mutuos y de inversión'), ('otros_intermediarios_financieros', 'Otros intermediarios financieros'), ('fondos_pensiones', 'Fondos de pensiones'), ('companias_seguros', 'Compañías de seguros'), ('gobierno_general', 'Gobierno general'), ('otros_sectores_residentes', 'Otros sectores residentes'), ('inversionistas_extranjeros', 'Inversionistas extranjeros')], max_length=50, null=True)),
                ('tipo_fila', models.CharField(choices=[('total_instrumento', 'Total del instrumento'), ('tenedor', 'Detalle por tenedor'), ('subconjunto', 'Subconjunto no aditivo (ej. Comprado en el ML)')], max_length=20)),
                ('anio', models.PositiveSmallIntegerField()),
                ('trimestre', models.PositiveSmallIntegerField()),
                ('fecha_corte', models.DateField()),
                ('monto_miles_millones_clp', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fuente', models.CharField(default='bcentral_emv_4', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['anio', 'trimestre'], name='data_engine_anio_dc3f1e_idx'), models.Index(fields=['instrumento', 'tenedor'], name='data_engine_instrum_711a35_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrumento', 'tenedor', 'tipo_fila', 'anio', 'trimestre'), name='uniq_stock_titulo_deuda')],
            },
        ),
    ]
