# Generated by Django 5.2.17 on 2026-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0003_stocktitulodeuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bono', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('es_reapertura', models.BooleanField(default=False)),
                ('moneda', models.CharField(choices=[('usd', 'Dólar estadounidense'), ('eur', 'Euro'), ('clp', 'Peso chileno')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=6, max_digits=18)),
                ('tasa_caratula_raw', models.CharField(max_length=100)),
                ('tasa_caratula_fija', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('tasa_bono_tesoro', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('tasa_local_tesoro_chile', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=8)),
                ('yield_emision', models.DecimalField(decimal_places=4, max_digits=8)),
                ('spread_caratula', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('spread_nota_referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('pago_intereses', models.CharField(choices=[('semestral', 'Semestral'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('vigencia', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido y pagado')], max_length=20)),
                ('fuente', models.CharField(default='hacienda_bonos_externos', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_emision'], name='data_engine_fecha_e_f33f20_idx'), models.Index(fields=['vigencia'], name='data_engine_vigenci_cd2b6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('nombre_bono', 'fecha_emision'), name='uniq_bono_externo')],
            },
        ),
    ]
