# Generated by Django 5.2.17 on 2026-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0004_bonoexterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonoexterno',
            name='yield_emision',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
