# Generated by Django 5.2.17 on 2026-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0005_alter_bonoexterno_yield_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bono', models.CharField(max_length=100)),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('es_reapertura', models.BooleanField(default=False)),
                ('tipo_instrumento', models.CharField(choices=[('btp', 'Bono de Tesorería en Pesos'), ('btu', 'Bono de Tesorería en UF'), ('letra', 'Letra del Tesoro')], max_length=10)),
                ('madurez_anios', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto_emitido', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('monto_colocado', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('tasa_caratula', models.DecimalField(decimal_places=4, max_digits=8)),
                ('paga_intereses_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido')], max_length=20)),
                ('fuente', models.CharField(default='hacienda_bonos_locales', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha_emision'], name='data_engine_fecha_e_7d48d0_idx'), models.Index(fields=['tipo_instrumento'], name='data_engine_tipo_in_762ca3_idx'), models.Index(fields=['status'], name='data_engine_status_bf331e_idx')],
                'constraints': [models.UniqueConstraint(fields=('nombre_bono', 'fecha_emision', 'fecha_vencimiento'), name='uniq_bono_local')],
            },
        ),
    ]
