# Generated by Django 5.2.17 on 2026-09-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0006_bonolocal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bonolocal',
            name='uniq_bono_local',
        ),
        migrations.AddConstraint(
            model_name='bonolocal',
            constraint=models.UniqueConstraint(fields=('nombre_bono', 'fecha_emision', 'fecha_vencimiento', 'anio'), name='uniq_bono_local'),
        ),
    ]
